<html>
<head>
    <title>VerifierScan</title>
    <link rel="icon" href="verifierscan_logo_2.png">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" integrity="sha384-1q8mTJOASx8j1Au+a5WDVnPi2lkFfwwEAa8hDDdjZlpLegxhjVME1fgjWPGmkzs7" crossorigin="anonymous">
    <link href="styles/style.css" rel="stylesheet">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.10.2/jquery.min.js"></script>
     <script>
		// Wait for window load
		$(window).load(function() {
			// Animate loader off screen
			$(".load-bar").hide();
		});
	</script>
</head>
<body>
<?php
include_once('functions.php');
//Define empty variables to avoid error
$org_score = "";
$url_score = "";
$security_score = "";
$spell_score = "";
$overall_score = "";
$org_letter = "";
$url_letter = "";
$sec_letter = "";
$spell_letter = "";
$ovr_letter = ""; 

if($_GET) {
    $base_domain = baseDomain($_GET['url']);

    $score = scoringFunction($_GET['url']);
    
    $org_letter = letterGrade($score['org']);
    $url_letter = letterGrade($score['url']);
    $sec_letter = letterGrade($score['sec']);
    $spell_letter = letterGrade($score['spell']);
    $ovr_letter = letterGrade($score['ovr']);    
    
}
?>
        <div class="col-md-12">
            <div class="panel panel-default">
                <div class="panel-body">
                   <!--CSS Loader-->
                   <div class="load-bar">
                      <div class="bar"></div>
                      <div class="bar"></div>
                      <div class="bar"></div>
                    </div>
                    <div>
                        <table class="table table-bordered table-striped">
                            <tr>
                                <td><b>Score Category</b></td>
                                <td><b>Score</b></td>
                                <td><b>Letter Grade</b></td>
                            </tr>
                            <tr>
                                <td>Source</td>
                                <td><?php echo $score['org']; ?></td>
                                <td><?php echo $org_letter['grade']; ?></td>
                            </tr>
                            <tr>
                                <td>URL</td>
                                <td><?php echo $score['url']; ?></td>
                                <td><?php echo $url_letter['grade']; ?></td>
                            </tr>
                            <tr>
                                <td>Site Security</td>
                                <td><?php echo $score['sec']; ?></td>
                                <td><?php echo $sec_letter['grade']; ?></td>
                            </tr>
                            <tr>
                                <td>Spelling</td>
                                <td><?php echo $score['spell']; ?></td>
                                <td><?php echo $spell_letter['grade']; ?></td>
                            </tr>
                            <tr class="result-row">
                                <td><b>Overall Score:</b></td>
                                <td style="color:<?php echo $ovr_letter['color'] ;?>"><b><?php echo $score['ovr']; ?></b></td>
                                <td style="color:<?php echo $ovr_letter['color'] ;?>"><b><?php echo $ovr_letter['grade']; ?></b></td>
                            </tr>
                        </table>
                    </div>
                    <small>*This score card is generated by a number of different factors and is not always accurate.</small>
                </div>
            </div>

    